config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'people#index'

  resources :people, shallow: true do
    resources :hobbies
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
# == Schema Information
#
# Table name: hobbies
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  kind        :integer
#  person_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_hobbies_on_person_id  (person_id)
#

class Hobby < ApplicationRecord
  enum kind: %i[indoors outdoors]

  belongs_to :person
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  birthdate  :date
#  gender     :integer
#  dni        :string
#  customer   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Person < ApplicationRecord
  enum gender: %i[male female unknown]
  has_many :hobbies
  validates :name, presence: true

  accepts_nested_attributes_for :hobbies, reject_if: proc { |attributes| attributes['name'].blank? }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  def new
    @person = Person.find_by(id: params[:person_id])
    @hobby = @person.hobbies.build
    @kinds = Hobby.kinds.keys
  end

  def create
    @person = Person.find_by(id: params[:person_id])
    @hobby = @person.hobbies.build(hobby_params)
    if @hobby.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def edit
    @hobby = Hobby.find(params[:id])
    @kinds = Hobby.kinds.keys
  end

  def update
    @hobby = Hobby.find(params[:id])
    if @hobby.update(hobby_params)
      redirect_to person_path(@hobby.person)
    else
      render :edit
    end

  end

  def destroy
    @hobby = Hobby.find(params[:id])
    @hobby.destroy
    redirect_to person_path(@hobby.person)
  end

  private

  def hobby_params
    params.require(:hobby).permit(:name, :description, :kind, :person_id)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
    @person = Person.new
  end

  def show
    @person = Person.find(params[:id])
    @hobby = @person.hobbies.build
  end

  def new
    @person = Person.new
    3.times do
      @person.hobbies.build
    end
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      respond_to do |format|
        format.html { redirect_to person_path(@person) }
        format.json { render json: @person }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @person.errors }
      end
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    @person.update(person_params)
    if @person.save
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit(:name, :email, :birthdate,
                                   :gender, :dni, :customer, hobbies_attributes: [:name, :description, :kind])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/hobbies/edit.html.haml
%h1 Hobbies#edit
%span
  = link_to('back', person_path(@hobby.person))

%br/
= form_with(model: @hobby, local: true) do |form|
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :description
    = form.text_area :description
  .field
    = form.label :kind
    = form.select :kind, options_for_select(@kinds)
  .field
    = form.hidden_field :person_id
  = form.submit

app/views/hobbies/new.html.haml
%h1 Hobbies#new
%span
  = link_to('back', person_path(@person))

%br/
= form_with(model: [@person, @hobby], local: true) do |form|
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :description
    = form.text_area :description
  .field
    = form.label :kind
    = form.select :kind, options_for_select(@kinds)
  .field
    = form.hidden_field :person_id
  = form.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title JavaScriptWebII
    = csrf_meta_tags
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      = yield

app/views/people/edit.html.haml
%h1 Edit Person
%br/
= form_with(model: @person, local: true) do |form|
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :email
    = form.email_field :email
  .field
    = form.label :birthdate
    = form.date_field :birthdate
  .field
    = form.label :gender
    = form.select :gender, [['Male', 'male'], ['Female', 'female'], ['unknown', 'unknown']]
  .field
    = form.label :dni
    = form.number_field :dni
  .field
    = form.label :customer?
    .field
      = form.label :yes
      = form.radio_button :customer, true
    .field
      = form.label :no
      = form.radio_button :customer, false, checked: true
  = form.submit

app/views/people/index.html.haml
.row.mb-4
  .col-12
    .alert.alert-primary{role: 'alert'}
      Clase Javascript Web II 02/02/2018
.row
  .col.text-center
    %h1 People

- if @people.empty?
  .row
    .col.text-center
      %h4 No People!
- else
  .d-flex.flex-row-reverse.mb-2
    .p-2
      %form.form-inline
        .input-group
          .input-group-prepend
            .input-group-text
              = fa_icon('search')
          = text_field :search, nil, class: 'form-control', placeholder: 'Type a name'
        %button.btn.btn-secundary.ml-1{type: 'submit'} Search
  .row
    .col
      %table.table
        %thead
          %tr
            %th Name
            %th Email
            %th Birthdate
            %th Gender
            %th DNI
            %th Customer?
            %th
        %tbody
          - @people.each do |person|
            %tr
              %td
                = link_to("#{person.name}", person_path(person), style: 'text-decoration: none; color: black')
              %td
                = person.email
              %td
                = person.birthdate
              %td
                = person.gender
              %td
                = person.dni
              %td
                = person.customer
              %td
                .btn-group
                  %button.btn.btn-secondary.dropdown-toggle{data: {toggle: 'dropdown'}}
                    Actions
                  .dropdown-menu.dropdown-menu-right
                    %button.dropdown-item{type: 'button'} Edit
                    .dropdown-divider
                    %button.dropdown-item{type: 'button'} Destroy
.row.mb-4
  .col
    = link_to('New Person', new_person_path, class: 'btn btn-primary')
    %button.btn.btn-success{"data-target" => "#ajaxPerson", "data-toggle" => "modal", :type => "button"} Ajax Person

#ajaxPerson.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "ajaxPersonLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %h5#ajaxPersonLabel.modal-title New Person
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      = form_with(model: @person, id: 'personForm', local: true ) do |form|
        .modal-body
          .row
            .col-6
              .form-group
                = form.label :name
                = form.text_field :name, class: 'form-control'
              .form-group
                = form.label :email
                = form.email_field :email, class: 'form-control'
              .form-group
                = form.label :birthdate
                = form.date_field :birthdate, class: 'form-control'
            .col-6
              .form-group
                = form.label :gender
                = form.select :gender, [['Male', 'male'], ['Female', 'female'], ['Unknown', 'unknown']], {}, class: 'form-control'
              .form-group
                = form.label :dni
                = form.number_field :dni, class: 'form-control'
              .form-group
                = form.label :customer?
                .form-check
                  = form.radio_button :customer, true, class: 'form-check-input', id: 'radio1'
                  = form.label :yes, class: 'form-check-label', for: 'radio1 '
                .form-check
                  = form.radio_button :customer, false, checked: true, class: 'form-check-input', id: 'radio2'
                  = form.label :no, class: 'form-check-label', for: 'radio2'
        .modal-footer
          %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
          = form.submit class: 'btn btn-primary'

app/views/people/new.html.haml
.row
  %h1 New Person
= form_with(model: @person, local: true) do |form|
  .row
    .col
      .form-group
        = form.label :name
        = form.text_field :name, class: 'form-control'
      .form-group
        = form.label :email
        = form.email_field :email, class: 'form-control'
      .form-group
        = form.label :birthdate
        = form.date_field :birthdate, class: 'form-control'
      .form-group
        = form.label :gender
        = form.select :gender, [['Male', 'male'], ['Female', 'female'], ['unknown', 'unknown']], {}, class: 'form-control'
      .form-group
        = form.label :dni
        = form.number_field :dni, class: 'form-control'
      .form-group
        = form.label :customer?
        .form-check
          = form.radio_button :customer, true, class: 'form-check-input', id: 'radio1'
          = form.label :yes, class: 'form-check-label', for: 'radio1 '
        .form-check
          = form.radio_button :customer, false, checked: true, class: 'form-check-input', id: 'radio2'
          = form.label :no, class: 'form-check-label', for: 'radio2'
      = form.submit class: 'btn btn-primary btn-block'
    .col
      = form.fields_for :hobbies do |hobby_fields|
        %h3= "Hobby ##{hobby_fields.index + 1}"
        .form-group
          = hobby_fields.text_field :name, placeholder: 'name', class: 'form-control'
        .form-group
          = hobby_fields.text_area :description, placeholder: 'description', class: 'form-control'
        .form-group
          = hobby_fields.label :kind
          = hobby_fields.select :kind, options_for_select(Hobby.kinds.keys), {}, class: 'form-control'

app/views/people/show.html.haml
.row.mb-4
  .col-12
    .card.w-75
      .card-header
        %h5.card-title
          =@person.name
          %span.badge.badge-secondary
            - if @person.customer?
              It's customer
            -else
              It's not customer
      .card-body
        .row
          .col-6
            .form-group
              %strong Email
              %p.card-text
                =@person.email
          .col-6
            .form-group
              %strong Birtdate
              %p.card-text
                = @person.birthdate
        .row
          .col-6
            .form-group
              %strong Gender
              %p.card-text
                = @person.gender
          .col-6
            .form-group
              %strong DNI
              %p.card-text
                = @person.dni
      .card-body.text-justify
        .btn-group{"aria-label" => "Basic example", :role => "group"}
          = link_to('Back', people_path, class: 'btn btn-secondary')
          = link_to('Edit', edit_person_path(@person), class: 'btn btn-secondary')
          = link_to('Destroy', person_path(@person), method: :delete, class: 'btn btn-secondary')

- if @person.hobbies.present?
  .row
    .col-12
      %h3 Hobibes
  - @person.hobbies.each do |hobby|
    - if hobby.persisted?
      .row.mb-5
        .col-12
          .card
            .card-body
              .card-title
                = hobby.name
                %span.float-right
                  = link_to(hobby_path(hobby), style: 'color: black', method: :delete) do
                    = fa_icon 'close'
              .card-text
                %p= hobby.description
                %p= hobby.kind

#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title New hobby
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      = form_with(model: [@person, @hobby], local: true) do |form|
        .modal-body
          .form-group
            = form.label :name
            = form.text_field :name, class: 'form-control'
          .form-group
            = form.label :description
            = form.text_area :description, class: 'form-control'
          .form-group
            = form.label :kind
            = form.select :kind, options_for_select(Hobby.kinds.keys), {}, class: 'form-control'
          .form-group
            = form.hidden_field :person_id
        .modal-footer
          %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
          = form.submit class: 'btn btn-primary'

%button.btn.btn-primary{"data-target" => "#exampleModal", "data-toggle" => "modal", :type => "button"}
  New Hobby